### ISSUE TITLE
How can I transform my kibana src to static version?

### ISSUE THREAD

**Issue by lwd426** [kibana-community/kibana4-static#2]
How can I transform my kibana src to static version?

**Comment by Asimov4** [comment]
I was following the steps listed here: https://github.com/elastic/kibana/issues/1628

**Comment by mbarman101** [comment]
How to get the adject source code of Kibana 4 in its static version ? Because I need to do some customization on it.

**Comment by lwd426** [comment]
You can get it from src/server/config/index.js.Of course,you must read the version of kibana in config/index.js.Just like the pic
![image](https://cloud.githubusercontent.com/assets/11454498/8476804/728084de-20f7-11e5-93ae-2489fef718be.png)
Do you understand what I mean?

**Comment by mbarman101** [comment]
I am not getting you correctly. I want to have  the full source code like the Kibana 4 server version have with all the html files and js files but not a single js file , so that I can customize it as per my needs and can run it within any server.(tomcat in my case)

**Comment by mbarman101** [comment]
Hi,
I am not getting you correctly. I want to have the full source code like
the Kibana 4 server version have with all the html files and js files but
not a single js file , so that I can customize it as per my needs and can
run it within any server.(tomcat in my case)

On Thu, Jul 2, 2015 at 5:48 PM, WeidongLiu <notifications@github.com> wrote:

> You can get it from src/server/config/index.js.Of course,you must read the
> version of kibana in config/index.js.Just like the pic
> [image: image]
> <https://cloud.githubusercontent.com/assets/11454498/8476804/728084de-20f7-11e5-93ae-2489fef718be.png>
> Do you understand what I mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kibana-community/kibana4-static/issues/2#issuecomment-118012296>
> .
>



-- 

*Thanks & Regards,Mrityunjay Barman*

*Sr. Software EngineerZaloni Technologies India Pvt. Ltd.*

*mbarman@zaloni.com <mbarman@zaloni.com>Mob: +91 9707344283*

This e-mail, including attachments, may include confidential
and/or proprietary information, and may be used only by the person or
entity to which it is addressed. If the reader of this e-mail is not the
intended recipient or his or her authorized agent, the reader is hereby
notifiedthat any dissemination, distribution or copying of this e-mail
is prohibited. If you have received this e-mail in error, please notify
the sender by replying to this message and delete this e-mail immediately.

**Comment by mbarman101** [comment]
I am not getting you correctly. I want to have the full source code like
the Kibana 4 server version have with all the html files and js files but
not a single js file , so that I can customize it as per my needs and can
run it within any server.(tomcat in my case)

On Thu, Jul 2, 2015 at 5:48 PM, WeidongLiu <notifications@github.com> wrote:

> You can get it from src/server/config/index.js.Of course,you must read the
> version of kibana in config/index.js.Just like the pic
> [image: image]
> <https://cloud.githubusercontent.com/assets/11454498/8476804/728084de-20f7-11e5-93ae-2489fef718be.png>
> Do you understand what I mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kibana-community/kibana4-static/issues/2#issuecomment-118012296>
> .
>



-- 

*Thanks & Regards,Mrityunjay Barman*

*Sr. Software EngineerZaloni Technologies India Pvt. Ltd.*

*mbarman@zaloni.com <mbarman@zaloni.com>Mob: +91 9707344283*

This e-mail, including attachments, may include confidential
and/or proprietary information, and may be used only by the person or
entity to which it is addressed. If the reader of this e-mail is not the
intended recipient or his or her authorized agent, the reader is hereby
notifiedthat any dissemination, distribution or copying of this e-mail
is prohibited. If you have received this e-mail in error, please notify
the sender by replying to this message and delete this e-mail immediately.

**Comment by lwd426** [comment]
Do you want to get the source code to do some secondary development? Get it from https://github.com/elastic/kibana .

**Comment by mbarman101** [comment]
Ya. But I want the static version but not with the integrated server. The static version of the Kibana 4 in git does not contain all the files rather contain a compiled one. So it will be great if you can help me with what do I need to change in the Kibana 4 code so that it can run without its integrated server.

**Comment by lwd426** [comment]
The code of kibana should not be changed.You must write the logic imitating src/server in your server(tomcat in your case).Did you studied the source code of kibana4?If you didn't,I'll say sorry that I can 't do anything to help you.

**Comment by Kranf99** [comment]
I'd like to be able to use the visual plugins built for kibana 4.4 inside "kibana static".
(I am stuck with kibana static for whatever reasons).
I had a brief discussion about this subject with Oleg Nenashev and he told me that it could be possible.
...but I am not a java guru.
Could somebody (maybe Asimov4?) do the required "upgrades" on "kibana static" to be able to use the visual plugins from the latest kibana ?
I have a small budget to do that.
